/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * File : GUI4.java
 * Deskripsi : Membuat JFrameForm dengan mengimplementasikan list, set, dan map
 * Pembuat :  Christianna Olivia Juniarti Manullang (24060124140168)
 * Tanggal : 28 Mei 2026 (Updated: 30 Mei 2026)
 */
import javax.swing.DefaultListModel;
import java.util.*;

public class GUI4 extends javax.swing.JFrame {
    
    // Atribut
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI4.class.getName());
    DefaultListModel<String> dlm;
    List<String> list = new ArrayList<>();
    Set<String> set = new HashSet<>();
    HashMap<Integer, String> map = new HashMap<>();

    /**
     * Creates new form GUI4
     */
    // Constructor
    public GUI4() {
        initComponents();
        dlm = new DefaultListModel<>();
        jListItem.setModel(dlm);
    }
    
    // Memperbaharui jumlah data tersimpan dalam list
    private void updateDTList(){
        jLabelDTList.setText(
                "Data tersimpan = " + list.size());
    }
    
    // Memperbaharui jumlah data tersimpan dalam set
    private void updateDTSet(){
        jLabelDTSet.setText(
                "Data tersimpan = " + set.size());
    }
    
    // Memperbaharui jumlah data tersimpan dalam map
    private void updateDTMap(){
        jLabelDTMap.setText(
                "Data tersimpan = " + map.size());
    }
    
    // Menambah item (string) baru ke dalam list dlm
    private void addItem(String namaItem){
        dlm.addElement(namaItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jButtonClearAll = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldItem = new javax.swing.JTextField();
        jLabelItemName = new javax.swing.JLabel();
        jButtonSaveToList = new javax.swing.JButton();
        jLabelDTList = new javax.swing.JLabel();
        jButtonInsDataList = new javax.swing.JButton();
        jButtonInsDataSet = new javax.swing.JButton();
        jButtonSaveToSet = new javax.swing.JButton();
        jLabelDTSet = new javax.swing.JLabel();
        jButtonInsDataMap = new javax.swing.JButton();
        jButtonSaveToMap = new javax.swing.JButton();
        jLabelDTMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jButtonClearAll.setText("clear all");
        jButtonClearAll.addActionListener(this::jButtonClearAllActionPerformed);

        jButtonAdd.setText("add");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonUpdate.setText("update");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jButtonDelete.setText("delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabelItemName.setText("Item name:");

        jButtonSaveToList.setText("save to List ->");
        jButtonSaveToList.addActionListener(this::jButtonSaveToListActionPerformed);

        jLabelDTList.setText("Data tersimpan = 0");

        jButtonInsDataList.setText("<- insert data List");
        jButtonInsDataList.addActionListener(this::jButtonInsDataListActionPerformed);

        jButtonInsDataSet.setText("<- insert data Set");
        jButtonInsDataSet.addActionListener(this::jButtonInsDataSetActionPerformed);

        jButtonSaveToSet.setText("save to Set ->");
        jButtonSaveToSet.addActionListener(this::jButtonSaveToSetActionPerformed);

        jLabelDTSet.setText("Data tersimpan = 0");

        jButtonInsDataMap.setText("<- insert data Map");
        jButtonInsDataMap.addActionListener(this::jButtonInsDataMapActionPerformed);

        jButtonSaveToMap.setText("save to Map ->");
        jButtonSaveToMap.addActionListener(this::jButtonSaveToMapActionPerformed);

        jLabelDTMap.setText("Data tersimpan = 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldItem)
                                    .addComponent(jLabelItemName)
                                    .addComponent(jButtonSaveToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInsDataList, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDTList))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSaveToSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInsDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDTSet))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSaveToMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInsDataMap, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDTMap))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToList)
                            .addComponent(jLabelDTList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToSet)
                            .addComponent(jLabelDTSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsDataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveToMap)
                            .addComponent(jLabelDTMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsDataMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearAll)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Tombol untuk menambah item
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        addItem(jTextFieldItem.getText());
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    // Tombol untuk memperbaharui item yang dipiilih
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldItem.getText();
        dlm.setElementAt(selected, index);
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    // Tombol untuk menghapus item
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    // Tombol untuk menghapus semua item dari dlm
    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        dlm.clear();
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    // Tombol untuk menyimpan data-data yang ada di dlm saat ini
    // ke list. Jika list terisi, list dikosongkan terlebih dahulu.
    private void jButtonSaveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToListActionPerformed
        if(!list.isEmpty()){
            list.clear();
        }
        for(int i = 0; i < dlm.getSize(); i++){
            list.add(dlm.getElementAt(i));
        }
        
        updateDTList();
    }//GEN-LAST:event_jButtonSaveToListActionPerformed

    // Tombol untuk menambahkan elemen-elemen dari list ke dlm
    // dlm tidak dikosongkan terlebih dahulu
    private void jButtonInsDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsDataListActionPerformed
        for(String item : list){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonInsDataListActionPerformed

    // Tombol untuk menyimpan data-data yang ada di dlm saat ini
    // ke set. Jika sey terisi, set dikosongkan terlebih dahulu.
    private void jButtonSaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToSetActionPerformed
        if(!set.isEmpty()){
            set.clear();
        }
        for(int i = 0; i < dlm.getSize(); i++){
            set.add(dlm.getElementAt(i));
        }
        
        updateDTSet();
    }//GEN-LAST:event_jButtonSaveToSetActionPerformed

    // Tombol untuk menambahkan elemen-elemen dari set ke dlm
    // dlm tidak dikosongkan terlebih dahulu
    private void jButtonInsDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsDataSetActionPerformed
        for(String item : set){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonInsDataSetActionPerformed

    // Tombol untuk menyimpan data-data yang ada di dlm saat ini
    // ke map. Jika map terisi, map dikosongkan terlebih dahulu.
    // key dibuat menggunakan indeks elemen, pada dlm, ditambah 1
    private void jButtonSaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveToMapActionPerformed
        if(!map.isEmpty()){
            map.clear();
        }
        for(int i = 0; i < dlm.getSize(); i++){
            map.put((i+1), dlm.getElementAt(i));
        }
        
        updateDTMap();
    }//GEN-LAST:event_jButtonSaveToMapActionPerformed

    // Tombol untuk menambahkan elemen-elemen dari map ke dlm
    // dlm tidak dikosongkan terlebih dahulu
    // key tidak dimasukkan, hanya value-nya saja
    private void jButtonInsDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsDataMapActionPerformed
        for(String item : map.values()){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonInsDataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsDataList;
    private javax.swing.JButton jButtonInsDataMap;
    private javax.swing.JButton jButtonInsDataSet;
    private javax.swing.JButton jButtonSaveToList;
    private javax.swing.JButton jButtonSaveToMap;
    private javax.swing.JButton jButtonSaveToSet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelDTList;
    private javax.swing.JLabel jLabelDTMap;
    private javax.swing.JLabel jLabelDTSet;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItem;
    // End of variables declaration//GEN-END:variables
}
